/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import java.io.IOException;
import java.awt.Dimension;
import WallPaper_Background.WallPaper_Background;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Logger;
import com.mycompany.project_version_02.MySQL_Connection;
import java.util.logging.Level;

/**
 *
 * @author JuanCin20
 */
public class Frame_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Employee
     *
     * @throws java.io.IOException
     */
    public Frame_Employee() throws IOException {
        initComponents();
        this.setSize(new Dimension(1350, 850));
        DesktopPane_01.setBorder(new WallPaper_Background());
        this.setExtendedState(Frame_Employee.MAXIMIZED_BOTH);
        this.setTitle("Pc - Factory Desktop App: Employee");
    }

    @Override
    public Image getIconImage() {
        Image Obj_Image = (Toolkit.getDefaultToolkit()).getImage("src//main//java//Imágenes//ToolKit.png");
        return Obj_Image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane_01 = new javax.swing.JDesktopPane();
        MenuBar_01 = new javax.swing.JMenuBar();
        Menu_01 = new javax.swing.JMenu();
        MenuItem_01 = new javax.swing.JMenuItem();
        Menu_02 = new javax.swing.JMenu();
        MenuItem_02 = new javax.swing.JMenuItem();
        Menu_03 = new javax.swing.JMenu();
        MenuItem_03 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        javax.swing.GroupLayout DesktopPane_01Layout = new javax.swing.GroupLayout(DesktopPane_01);
        DesktopPane_01.setLayout(DesktopPane_01Layout);
        DesktopPane_01Layout.setHorizontalGroup(
            DesktopPane_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1660, Short.MAX_VALUE)
        );
        DesktopPane_01Layout.setVerticalGroup(
            DesktopPane_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        MenuBar_01.setPreferredSize(new java.awt.Dimension(1465, 50));

        Menu_01.setIcon(new ImageIcon("src//main//java//Imágenes//User_01.png"));
        Menu_01.setText("Clientes");
        Menu_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_01.setPreferredSize(new java.awt.Dimension(165, 38));

        MenuItem_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_01.setIcon(new ImageIcon("src//main//java//Imágenes//Add.png"));
        MenuItem_01.setText("Nuevo Cliente");
        MenuItem_01.setPreferredSize(new java.awt.Dimension(165, 35));
        MenuItem_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_01ActionPerformed(evt);
            }
        });
        Menu_01.add(MenuItem_01);

        MenuBar_01.add(Menu_01);

        Menu_02.setIcon(new ImageIcon("src//main//java//Imágenes//Cart.png"));
        Menu_02.setText("Realizar Pedido");
        Menu_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_02.setPreferredSize(new java.awt.Dimension(220, 38));

        MenuItem_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_02.setIcon(new ImageIcon("src//main//java//Imágenes//Cart.png"));
        MenuItem_02.setText("Realizar Pedido");
        MenuItem_02.setPreferredSize(new java.awt.Dimension(220, 35));
        MenuItem_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_02ActionPerformed(evt);
            }
        });
        Menu_02.add(MenuItem_02);

        MenuBar_01.add(Menu_02);

        Menu_03.setIcon(new ImageIcon("src//main//java//Imágenes//Log_Out.png"));
        Menu_03.setText("Cerrar Sesión");
        Menu_03.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_03.setPreferredSize(new java.awt.Dimension(220, 38));

        MenuItem_03.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_03.setIcon(new ImageIcon("src//main//java//Imágenes//Log_Out.png"));
        MenuItem_03.setText("Cerrar Sesión");
        MenuItem_03.setPreferredSize(new java.awt.Dimension(220, 35));
        MenuItem_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_03ActionPerformed(evt);
            }
        });
        Menu_03.add(MenuItem_03);

        MenuBar_01.add(Menu_03);

        setJMenuBar(MenuBar_01);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane_01)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane_01, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_02ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Sell Obj_InternalFrame_New_Sell = null;
        try {
            Obj_InternalFrame_New_Sell = new InternalFrame_New_Sell();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_New_Sell);
        Obj_InternalFrame_New_Sell.setVisible(true);
    }//GEN-LAST:event_MenuItem_02ActionPerformed

    private void MenuItem_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_03ActionPerformed
        // TODO add your handling code here:
        Frame_Log_In Obj_Frame_Log_In = new Frame_Log_In();
        Obj_Frame_Log_In.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItem_03ActionPerformed

    private void MenuItem_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_01ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Customer Obj_InternalFrame_New_Customer = new InternalFrame_New_Customer();
        DesktopPane_01.add(Obj_InternalFrame_New_Customer);
        Obj_InternalFrame_New_Customer.setVisible(true);
    }//GEN-LAST:event_MenuItem_01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frame_Employee().setVisible(true);
                } catch (IOException Obj_IOException) {
                    Logger.getLogger(WallPaper_Background.class.getName()).log(Level.SEVERE, Obj_IOException.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane_01;
    private javax.swing.JMenuBar MenuBar_01;
    private javax.swing.JMenuItem MenuItem_01;
    private javax.swing.JMenuItem MenuItem_02;
    private javax.swing.JMenuItem MenuItem_03;
    private javax.swing.JMenu Menu_01;
    private javax.swing.JMenu Menu_02;
    private javax.swing.JMenu Menu_03;
    // End of variables declaration//GEN-END:variables
}