/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import java.io.IOException;
import java.awt.Dimension;
import WallPaper_Background.WallPaper_Background;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Logger;
import com.mycompany.project_version_02.MySQL_Connection;
import java.util.logging.Level;

/**
 *
 * @author JuanCin20
 */
public class Frame_Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Administrator
     *
     * @throws java.io.IOException
     */
    public Frame_Administrator() throws IOException {
        initComponents();
        this.setSize(new Dimension(1660, 750));
        DesktopPane_01.setBorder(new WallPaper_Background());
        this.setExtendedState(Frame_Administrator.MAXIMIZED_BOTH);
        this.setTitle("Pc - Factory Desktop App: Administrator");
    }

    @Override
    public Image getIconImage() {
        Image Obj_Image = (Toolkit.getDefaultToolkit()).getImage("src//main//java//Imágenes//ToolKit.png");
        return Obj_Image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane_01 = new javax.swing.JDesktopPane();
        MenuBar_01 = new javax.swing.JMenuBar();
        Menu_01 = new javax.swing.JMenu();
        MenuItem_01 = new javax.swing.JMenuItem();
        MenuItem_02 = new javax.swing.JMenuItem();
        Menu_02 = new javax.swing.JMenu();
        MenuItem_03 = new javax.swing.JMenuItem();
        MenuItem_04 = new javax.swing.JMenuItem();
        Menu_03 = new javax.swing.JMenu();
        MenuItem_05 = new javax.swing.JMenuItem();
        MenuItem_06 = new javax.swing.JMenuItem();
        Menu_04 = new javax.swing.JMenu();
        MenuItem_07 = new javax.swing.JMenuItem();
        MenuItem_08 = new javax.swing.JMenuItem();
        Menu_05 = new javax.swing.JMenu();
        MenuItem_09 = new javax.swing.JMenuItem();
        Menu_06 = new javax.swing.JMenu();
        MenuItem_10 = new javax.swing.JMenuItem();
        Menu_07 = new javax.swing.JMenu();
        MenuItem_11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        DesktopPane_01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout DesktopPane_01Layout = new javax.swing.GroupLayout(DesktopPane_01);
        DesktopPane_01.setLayout(DesktopPane_01Layout);
        DesktopPane_01Layout.setHorizontalGroup(
            DesktopPane_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1660, Short.MAX_VALUE)
        );
        DesktopPane_01Layout.setVerticalGroup(
            DesktopPane_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        MenuBar_01.setPreferredSize(new java.awt.Dimension(1465, 50));

        Menu_01.setIcon(new ImageIcon("src//main//java//Imágenes//User_01.png"));
        Menu_01.setText("Usuarios");
        Menu_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_01.setPreferredSize(new java.awt.Dimension(165, 38));

        MenuItem_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_01.setIcon(new ImageIcon("src//main//java//Imágenes//Add.png"));
        MenuItem_01.setText("Nuevo Usuario");
        MenuItem_01.setPreferredSize(new java.awt.Dimension(165, 35));
        MenuItem_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_01ActionPerformed(evt);
            }
        });
        Menu_01.add(MenuItem_01);

        MenuItem_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_02.setIcon(new ImageIcon("src//main//java//Imágenes//Management.png"));
        MenuItem_02.setText("Gestionar Usuarios");
        MenuItem_02.setPreferredSize(new java.awt.Dimension(165, 35));
        MenuItem_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_02ActionPerformed(evt);
            }
        });
        Menu_01.add(MenuItem_02);

        MenuBar_01.add(Menu_01);

        Menu_02.setIcon(new ImageIcon("src//main//java//Imágenes//Category.png"));
        Menu_02.setText("Categorías de Productos");
        Menu_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_02.setPreferredSize(new java.awt.Dimension(320, 38));

        MenuItem_03.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_03.setIcon(new ImageIcon("src//main//java//Imágenes//Add.png"));
        MenuItem_03.setText("Nueva Categoría de Producto");
        MenuItem_03.setPreferredSize(new java.awt.Dimension(320, 35));
        MenuItem_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_03ActionPerformed(evt);
            }
        });
        Menu_02.add(MenuItem_03);

        MenuItem_04.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_04.setIcon(new ImageIcon("src//main//java//Imágenes//Management.png"));
        MenuItem_04.setText("Gestionar Categorías de Productos");
        MenuItem_04.setPreferredSize(new java.awt.Dimension(320, 35));
        MenuItem_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_04ActionPerformed(evt);
            }
        });
        Menu_02.add(MenuItem_04);

        MenuBar_01.add(Menu_02);

        Menu_03.setIcon(new ImageIcon("src//main//java//Imágenes//Brand.png"));
        Menu_03.setText("Marcas de Productos");
        Menu_03.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_03.setMinimumSize(new java.awt.Dimension(280, 38));
        Menu_03.setPreferredSize(new java.awt.Dimension(280, 38));

        MenuItem_05.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_05.setIcon(new ImageIcon("src//main//java//Imágenes//Add.png"));
        MenuItem_05.setText("Nueva Marca de Producto");
        MenuItem_05.setPreferredSize(new java.awt.Dimension(280, 35));
        MenuItem_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_05ActionPerformed(evt);
            }
        });
        Menu_03.add(MenuItem_05);

        MenuItem_06.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_06.setIcon(new ImageIcon("src//main//java//Imágenes//Management.png"));
        MenuItem_06.setText("Gestionar Marcas de Productos");
        MenuItem_06.setPreferredSize(new java.awt.Dimension(280, 35));
        MenuItem_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_06ActionPerformed(evt);
            }
        });
        Menu_03.add(MenuItem_06);

        MenuBar_01.add(Menu_03);

        Menu_04.setIcon(new ImageIcon("src//main//java//Imágenes//Product.png"));
        Menu_04.setText("Productos");
        Menu_04.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_04.setMinimumSize(new java.awt.Dimension(175, 38));
        Menu_04.setPreferredSize(new java.awt.Dimension(175, 38));

        MenuItem_07.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_07.setIcon(new ImageIcon("src//main//java//Imágenes//Add.png"));
        MenuItem_07.setText("Nuevo Producto");
        MenuItem_07.setPreferredSize(new java.awt.Dimension(175, 35));
        MenuItem_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_07ActionPerformed(evt);
            }
        });
        Menu_04.add(MenuItem_07);

        MenuItem_08.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_08.setIcon(new ImageIcon("src//main//java//Imágenes//Management.png"));
        MenuItem_08.setText("Gestionar Productos");
        MenuItem_08.setPreferredSize(new java.awt.Dimension(175, 35));
        MenuItem_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_08ActionPerformed(evt);
            }
        });
        Menu_04.add(MenuItem_08);

        MenuBar_01.add(Menu_04);

        Menu_05.setIcon(new ImageIcon("src//main//java//Imágenes//Cart.png"));
        Menu_05.setText("Realizar Pedido");
        Menu_05.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_05.setPreferredSize(new java.awt.Dimension(220, 38));

        MenuItem_09.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_09.setIcon(new ImageIcon("src//main//java//Imágenes//Cart.png"));
        MenuItem_09.setText("Realizar Pedido");
        MenuItem_09.setPreferredSize(new java.awt.Dimension(220, 35));
        MenuItem_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_09ActionPerformed(evt);
            }
        });
        Menu_05.add(MenuItem_09);

        MenuBar_01.add(Menu_05);

        Menu_06.setIcon(new ImageIcon("src//main//java//Imágenes//Record.png"));
        Menu_06.setText("Historial de Pedidos");
        Menu_06.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_06.setPreferredSize(new java.awt.Dimension(270, 38));

        MenuItem_10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_10.setIcon(new ImageIcon("src//main//java//Imágenes//Record.png"));
        MenuItem_10.setText("Historial de Pedidos");
        MenuItem_10.setPreferredSize(new java.awt.Dimension(270, 35));
        MenuItem_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_10ActionPerformed(evt);
            }
        });
        Menu_06.add(MenuItem_10);

        MenuBar_01.add(Menu_06);

        Menu_07.setIcon(new ImageIcon("src//main//java//Imágenes//Log_Out.png"));
        Menu_07.setText("Cerrar Sesión");
        Menu_07.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Menu_07.setPreferredSize(new java.awt.Dimension(200, 38));

        MenuItem_11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        MenuItem_11.setIcon(new ImageIcon("src//main//java//Imágenes//Log_Out.png"));
        MenuItem_11.setText("Cerrar Sesión");
        MenuItem_11.setPreferredSize(new java.awt.Dimension(200, 35));
        MenuItem_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_11ActionPerformed(evt);
            }
        });
        Menu_07.add(MenuItem_11);

        MenuBar_01.add(Menu_07);

        setJMenuBar(MenuBar_01);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane_01)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane_01)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_01ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_User Obj_InternalFrame_New_User = new InternalFrame_New_User();
        DesktopPane_01.add(Obj_InternalFrame_New_User);
        Obj_InternalFrame_New_User.setVisible(true);
    }//GEN-LAST:event_MenuItem_01ActionPerformed

    private void MenuItem_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_02ActionPerformed
        // TODO add your handling code here:
        InternalFrame_Management_Users Obj_InternalFrame_Management_Users = null;
        try {
            Obj_InternalFrame_Management_Users = new InternalFrame_Management_Users();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_Management_Users);
        Obj_InternalFrame_Management_Users.setVisible(true);
    }//GEN-LAST:event_MenuItem_02ActionPerformed

    private void MenuItem_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_03ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Product_Category Obj_InternalFrame_New_Product_Category = new InternalFrame_New_Product_Category();
        DesktopPane_01.add(Obj_InternalFrame_New_Product_Category);
        Obj_InternalFrame_New_Product_Category.setVisible(true);
    }//GEN-LAST:event_MenuItem_03ActionPerformed

    private void MenuItem_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_04ActionPerformed
        // TODO add your handling code here:
        InternalFrame_Management_Products_Categories Obj_InternalFrame_Management_Products_Categories = null;
        try {
            Obj_InternalFrame_Management_Products_Categories = new InternalFrame_Management_Products_Categories();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_Management_Products_Categories);
        Obj_InternalFrame_Management_Products_Categories.setVisible(true);
    }//GEN-LAST:event_MenuItem_04ActionPerformed

    private void MenuItem_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_05ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Product_Brand Obj_InternalFrame_New_Product_Brand = new InternalFrame_New_Product_Brand();
        DesktopPane_01.add(Obj_InternalFrame_New_Product_Brand);
        Obj_InternalFrame_New_Product_Brand.setVisible(true);
    }//GEN-LAST:event_MenuItem_05ActionPerformed

    private void MenuItem_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_06ActionPerformed
        // TODO add your handling code here:
        InternalFrame_Management_Products_Brands Obj_InternalFrame_Management_Products_Brands = null;
        try {
            Obj_InternalFrame_Management_Products_Brands = new InternalFrame_Management_Products_Brands();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_Management_Products_Brands);
        Obj_InternalFrame_Management_Products_Brands.setVisible(true);
    }//GEN-LAST:event_MenuItem_06ActionPerformed

    private void MenuItem_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_07ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Product Obj_InternalFrame_New_Product = new InternalFrame_New_Product();
        DesktopPane_01.add(Obj_InternalFrame_New_Product);
        Obj_InternalFrame_New_Product.setVisible(true);
    }//GEN-LAST:event_MenuItem_07ActionPerformed

    private void MenuItem_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_08ActionPerformed
        // TODO add your handling code here:
        InternalFrame_Management_Products Obj_InternalFrame_Management_Products = null;
        try {
            Obj_InternalFrame_Management_Products = new InternalFrame_Management_Products();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_Management_Products);
        Obj_InternalFrame_Management_Products.setVisible(true);
    }//GEN-LAST:event_MenuItem_08ActionPerformed

    private void MenuItem_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_11ActionPerformed
        // TODO add your handling code here:
        Frame_Log_In Obj_Frame_Log_In = new Frame_Log_In();
        Obj_Frame_Log_In.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItem_11ActionPerformed

    private void MenuItem_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_09ActionPerformed
        // TODO add your handling code here:
        InternalFrame_New_Sell Obj_InternalFrame_New_Sell = null;
        try {
            Obj_InternalFrame_New_Sell = new InternalFrame_New_Sell();
        } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
            Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, null, Obj_SQLException_ClassNotFoundException.getMessage());
        }
        DesktopPane_01.add(Obj_InternalFrame_New_Sell);
        Obj_InternalFrame_New_Sell.setVisible(true);
    }//GEN-LAST:event_MenuItem_09ActionPerformed

    private void MenuItem_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_10ActionPerformed
        // TODO add your handling code here:
        InternalFrame_Management_Sells Obj_InternalFrame_Management_Sells = new InternalFrame_Management_Sells();
        DesktopPane_01.add(Obj_InternalFrame_Management_Sells);
        Obj_InternalFrame_Management_Sells.setVisible(true);
    }//GEN-LAST:event_MenuItem_10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frame_Administrator().setVisible(true);
                } catch (IOException Obj_IOException) {
                    Logger.getLogger(WallPaper_Background.class.getName()).log(Level.SEVERE, Obj_IOException.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane_01;
    private javax.swing.JMenuBar MenuBar_01;
    private javax.swing.JMenuItem MenuItem_01;
    private javax.swing.JMenuItem MenuItem_02;
    private javax.swing.JMenuItem MenuItem_03;
    private javax.swing.JMenuItem MenuItem_04;
    private javax.swing.JMenuItem MenuItem_05;
    private javax.swing.JMenuItem MenuItem_06;
    private javax.swing.JMenuItem MenuItem_07;
    private javax.swing.JMenuItem MenuItem_08;
    private javax.swing.JMenuItem MenuItem_09;
    private javax.swing.JMenuItem MenuItem_10;
    private javax.swing.JMenuItem MenuItem_11;
    private javax.swing.JMenu Menu_01;
    private javax.swing.JMenu Menu_02;
    private javax.swing.JMenu Menu_03;
    private javax.swing.JMenu Menu_04;
    private javax.swing.JMenu Menu_05;
    private javax.swing.JMenu Menu_06;
    private javax.swing.JMenu Menu_07;
    // End of variables declaration//GEN-END:variables
}