/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.UIManager;
import Controlador.Controlador_Categoria_Producto;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.SQLException;
import java.util.logging.Logger;
import com.mycompany.project_version_02.MySQL_Connection;
import java.util.logging.Level;
import Modelo.Modelo_Categoria_Producto;

/**
 *
 * @author JuanCin20
 */
public class InternalFrame_New_Product_Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_New__Product_Cateogry
     */
    public InternalFrame_New_Product_Category() {
        initComponents();
        this.setTitle("Pc - Factory Desktop App: New Product Category");
        UIManager.put("OptionPane.okButtonText", "Aceptar");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
    }

    private final Controlador_Categoria_Producto Obj_Controlador_Categoria_Producto = new Controlador_Categoria_Producto();

    private void Show_Confirm_Dialog() {
        InternalFrame_New_Product_Category Obj_InternalFrame_New_Product_Category = new InternalFrame_New_Product_Category();
        TextField_01.setBackground(Color.BLUE);
        TextField_01.setText("");
        TextArea_01.setBackground(Color.BLUE);
        TextArea_01.setText("");

        int Option_Selected = JOptionPane.showConfirmDialog(null, "Categoría del Producto Registrada Correctamente.", "Información", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);

        switch (Option_Selected) {
            case -1 -> {
                this.dispose();
                Frame_Administrator.DesktopPane_01.add(Obj_InternalFrame_New_Product_Category);
                Obj_InternalFrame_New_Product_Category.setVisible(true);
                System.out.println("Option_Selected: " + Option_Selected);
            }
            case 0 -> {
                this.dispose();
                Frame_Administrator.DesktopPane_01.add(Obj_InternalFrame_New_Product_Category);
                Obj_InternalFrame_New_Product_Category.setVisible(true);
                System.out.println("Option_Selected: " + Option_Selected);
            }
            default ->
                System.out.println("Switch_Default_Case");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_01 = new javax.swing.JPanel();
        Label_02 = new javax.swing.JLabel();
        Label_03 = new javax.swing.JLabel();
        TextField_01 = new javax.swing.JTextField();
        ScrollPane_01 = new javax.swing.JScrollPane();
        TextArea_01 = new javax.swing.JTextArea();
        Panel_02 = new javax.swing.JPanel();
        Button_01 = new javax.swing.JButton();
        Button_02 = new javax.swing.JButton();
        Label_01 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_01.setBackground(new java.awt.Color(102, 102, 102));
        Panel_01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Label_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Label_02.setForeground(new java.awt.Color(255, 255, 255));
        Label_02.setIcon(new ImageIcon("src//main//java//Imágenes//Category.png"));
        Label_02.setText("Nombre:");

        Label_03.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Label_03.setForeground(new java.awt.Color(255, 255, 255));
        Label_03.setIcon(new ImageIcon("src//main//java//Imágenes//Category.png"));
        Label_03.setText("Descripción:");

        TextField_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

        TextArea_01.setColumns(20);
        TextArea_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        TextArea_01.setRows(5);
        ScrollPane_01.setViewportView(TextArea_01);

        javax.swing.GroupLayout Panel_01Layout = new javax.swing.GroupLayout(Panel_01);
        Panel_01.setLayout(Panel_01Layout);
        Panel_01Layout.setHorizontalGroup(
            Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_02, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_03, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_01, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPane_01))
                .addContainerGap())
        );
        Panel_01Layout.setVerticalGroup(
            Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_02, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_01, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_03, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPane_01, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(Panel_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 465, 215));

        Panel_02.setBackground(new java.awt.Color(102, 102, 102));
        Panel_02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Button_01.setBackground(new java.awt.Color(51, 204, 0));
        Button_01.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Button_01.setText("Insertar");
        Button_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_01ActionPerformed(evt);
            }
        });

        Button_02.setBackground(new java.awt.Color(255, 0, 0));
        Button_02.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Button_02.setText("Volver");
        Button_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_02Layout = new javax.swing.GroupLayout(Panel_02);
        Panel_02.setLayout(Panel_02Layout);
        Panel_02Layout.setHorizontalGroup(
            Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_02, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_01, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Panel_02Layout.setVerticalGroup(
            Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_01, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_02, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Panel_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 120, 80));

        Label_01.setIcon(new ImageIcon("src//main//java//Imágenes//Wallpaper_03.png"));
        getContentPane().add(Label_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_01ActionPerformed
        // TODO add your handling code here:
        if ((TextField_01.getText()).isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Campo Requerido: Nombre de la Categoría del Producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            TextField_01.setBackground(Color.RED);
            TextField_01.requestFocus();
        } else {
            if ((TextArea_01.getText()).isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Campo Requerido: Descripción de la Categoría del Producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                TextArea_01.setBackground(Color.RED);
                TextArea_01.requestFocus();
            } else {

                String Nombre_Categoria_Producto = (TextField_01.getText()).trim();
                String Descripcion_Categoria_Producto = (TextArea_01.getText()).trim();

                LocalDateTime Obj_LocalDateTime = LocalDateTime.now();
                DateTimeFormatter Obj_DateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String Fecha_Registro_Categoria_Producto = Obj_LocalDateTime.format(Obj_DateTimeFormatter);

                if ((Nombre_Categoria_Producto.length()) > 50) {
                    JOptionPane.showMessageDialog(null, "El Nombre debe Contener un Máximo de 50 Caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    TextField_01.setBackground(Color.RED);
                    TextField_01.setText("");
                    TextField_01.requestFocus();
                } else {
                    try {
                        if (Obj_Controlador_Categoria_Producto.Check_Nombre_Categoria_Producto(Nombre_Categoria_Producto) == true) {
                            JOptionPane.showMessageDialog(null, "El Nombre ya se Encuentra Registrado en la Base de Datos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            TextField_01.setBackground(Color.RED);
                            TextField_01.setText("");
                            TextField_01.requestFocus();
                        } else {
                            TextField_01.setBackground(Color.GREEN);
                            System.out.println("Nombre_Categoria_Producto: Ok!.");
                        }
                    } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
                        Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, Obj_SQLException_ClassNotFoundException.getMessage());
                    }
                }

                if ((Descripcion_Categoria_Producto.length()) > 260) {
                    JOptionPane.showMessageDialog(null, "La Descripción debe Contener un Máximo de 260 Caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    TextArea_01.setBackground(Color.RED);
                    TextArea_01.setText("");
                    TextArea_01.requestFocus();
                } else {
                    TextArea_01.setBackground(Color.GREEN);
                    System.out.println("Descripcion_Categoria_Producto: Ok!.");
                }

                if ((TextField_01.getText()).isEmpty() == true || (TextArea_01.getText()).isEmpty() == true) {
                    System.out.println("Try Again!");
                } else {
                    Modelo_Categoria_Producto Obj_Modelo_Categoria_Producto = new Modelo_Categoria_Producto();

                    Obj_Modelo_Categoria_Producto.setNombre_Categoria_Producto(Nombre_Categoria_Producto);
                    Obj_Modelo_Categoria_Producto.setDescripcion_Categoria_Producto(Descripcion_Categoria_Producto);
                    Obj_Modelo_Categoria_Producto.setEstado_Categoria_Producto(false);
                    Obj_Modelo_Categoria_Producto.setFecha_Registro_Categoria_Producto(Fecha_Registro_Categoria_Producto);

                    try {
                        if (Obj_Controlador_Categoria_Producto.Insertar_Categoria_Producto(Obj_Modelo_Categoria_Producto) == true) {
                            this.Show_Confirm_Dialog();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Registrar la Categoría del Producto.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException | ClassNotFoundException Obj_SQLException_ClassNotFoundException) {
                        Logger.getLogger(MySQL_Connection.class.getName()).log(Level.SEVERE, Obj_SQLException_ClassNotFoundException.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_Button_01ActionPerformed

    private void Button_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_02ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Button_02ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_01;
    private javax.swing.JButton Button_02;
    private javax.swing.JLabel Label_01;
    private javax.swing.JLabel Label_02;
    private javax.swing.JLabel Label_03;
    private javax.swing.JPanel Panel_01;
    private javax.swing.JPanel Panel_02;
    private javax.swing.JScrollPane ScrollPane_01;
    private javax.swing.JTextArea TextArea_01;
    private javax.swing.JTextField TextField_01;
    // End of variables declaration//GEN-END:variables
}